### ISSUE TITLE
Ctrl+c interrupts swallowed

### ISSUE THREAD

**Issue by theothertomelliott** [bcicen/ctop#1]
Not sure if this is intentional, but ctop doesn't respond to ctrl+c, which was the first thing I'd naturally try to exit a new command-line application.

On first use, I ended up killing my terminal session, before getting to the end of the README for the list of commands.

**Comment by bcicen** [comment]
Good point. I've added ctrl+c exit handling in https://github.com/bcicen/ctop/commit/2f17a9d6894adbc6259cef64f656bc38c1182afd, and the latest release has been updated to include this as well.

Thanks for the feedback!
