### ISSUE TITLE
Put sha256sum to every release page info

### ISSUE THREAD

**Issue by ronnicek** [bcicen/ctop#100]
Hi,

could you please add sha256sum to release page info for every release that I can check that what I download is right? :) (you can check docker-compose for example of that).

Thanks! :)

**Comment by bcicen** [comment]
@ronnicek certainly; thanks for the suggestion!

`sha256sums.txt` appended to the [latest release](https://github.com/bcicen/ctop/releases/tag/v0.6.1), and will be automatically included in all future releases.
