### ISSUE TITLE
Report Generator Required

### ISSUE THREAD

**Issue by adic26** [bcicen/ctop#101]
Love this tool!  However, as a DevOps engineer I would like to integrate this as part of my pipeline - but there is no report generation feature that I would integrate part of automation.

Unless I am mistaken, does this feature exist?

**Comment by pete911** [comment]
I don't think that this tool is a good fit for pipeline. Ideally you would want to run something as a service in the pipeline. I would expect that there are already some existing tools (like cadvisor) for this. Plus you would want to have something where you could set you thresholds so you can fail the build etc.

Maybe what could help would be to split the project into different projects, one just pure UI, second backend? Or just user docker api for your use cases? looks like they will be very specific?

**Comment by adic26** [comment]
Okay thanks. I'll look for other tools.
