### ISSUE TITLE
Fatal error on start

### ISSUE THREAD

**Issue by pingmurder** [bcicen/ctop#102]
CentOS openvz server - 
error: Get http://unix.sock/containers/json?all=1: dial unix /var/run/docker.sock: connect: no such file or directory

**Comment by bcicen** [comment]
What is the output of `env | grep ^DOCKER`? By default, your `DOCKER_HOST` variable should be empty or set to `unix:///var/run/docker.sock`

**Comment by bcicen** [comment]
closing for now
