### ISSUE TITLE
Toggle timestamps in log view

### ISSUE THREAD

**Issue by bcicen** [bcicen/ctop#107]
Allow container log timestamps to optionally be shown alongside log lines

**Comment by pete911** [comment]
how would you want to do this? Would toggling be when inside log view, or outside (like verbose or something that could be in config as well?) What key binding were you thinking of?

**Comment by pete911** [comment]
I'm thinking that `L` could be logs with timestamps, `l` without (as it is now).

**Comment by bcicen** [comment]
having the toggle handler defined within the `LogMenu` (`t` keybinding perhaps) and using the existing "exit" keys to escape the view would likely be best.

Using the same timestamp format as `docker logs` with a truncated nanosecond field would likely be the most familiar to users: `2017-12-05T00:54:38.892Z`

**Comment by pete911** [comment]
PR raised - #110
