### ISSUE TITLE
Twice of dependencies updating

### ISSUE THREAD

**Issue by sah4ez** [bcicen/ctop#109]
When I build docker image via `make image`, I found twice of dependencies updating:
1. In `Makefile` in target `build` 
```
build:
    dep ensure
    CGO_ENABLED=0 go build -tags release -ldflags $(LD_FLAGS) -o ctop
```
2. In `Dockerfile` on 7 line
```
RUN dep ensure -vendor-only
```
and run `make build` on 10 line.
It is do special or it typo?

**Comment by bcicen** [comment]
`-vendor-only` allows the dependencies to be installed having only the `Gopkg.*` files available. This allows the dep step to be cached in the docker build process, speeding up future local image builds.
