### ISSUE TITLE
Example how to run it in docker

### ISSUE THREAD

**Issue by korczis** [bcicen/ctop#11]
It will be nice if the example how to run ctop in container (and what and where to mount) is provided. 

Especially for us, CoreOS users.

**Comment by francislavoie** [comment]
Pretty sure all it needs is the `DOCKER_HOST` env var, and `/var/run/docker.sock`, e.g. `-v /var/run/docker.sock:/var/run/docker.sock`

Probably would be ideal to have a Dockerfile in the project to build it.

**Comment by francislavoie** [comment]
I made a Dockerfile here https://github.com/bcicen/ctop/pull/14

**Comment by bcicen** [comment]
added official alpine-based image and doc in https://github.com/bcicen/ctop/commit/c84b52ce40085bd3448906ab7ee29f6eecda92cc
