### ISSUE TITLE
'm' key can not work

### ISSUE THREAD

**Issue by zxl777** [bcicen/ctop#114]
When i press 'm' key ,nothing happened.

Maybe a bug ?

**Comment by pete911** [comment]
Looks like it has not been released, [latest release](https://github.com/bcicen/ctop/releases) is from 12 Jul 2017. If you want all the latest features, best would be to [build](https://github.com/bcicen/ctop/blob/master/_docs/build.md) from master.

**Comment by bcicen** [comment]
container menu keybinding has been changed to `<enter>` in the latest [v0.7 release](https://github.com/bcicen/ctop/releases/latest).

In the future, the latest build of ctop is always available via the hosted image described in the README as well
