### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by mrichman** [bcicen/ctop#115]
Does this work on Windows? If so, a Windows binary release would be much appreciated!

**Comment by bcicen** [comment]
I don't have a native way of completely testing this at the moment; however, I've added a candidate Windows build to the [latest release](https://github.com/bcicen/ctop/releases/tag/v0.7) -- feel free to update this issue with any problems encountered.

**Comment by bcicen** [comment]
Closing for now; please open new issue with any Windows compat issues
