### ISSUE TITLE
A little conflict of names

### ISSUE THREAD

**Issue by cr6git** [bcicen/ctop#116]
Hi !

I would like to package your stuff for Void linux, however there's a little problem:

We alreay have a package called `ctop` in the repos, see [here](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/ctop/template).
The source comes from [yadutaf/ctop](https://github.com/yadutaf/ctop).

You are two different projects but you share the same name, it's confusing...
So I don't know what name to chose for my package.
I hope you understand.

Regards.

**Comment by cr6git** [comment]
Your program fails to build, perhaps something is wrong in your code?

I stopped working on this, so I close the issue.

**Comment by bcicen** [comment]
While I'm unsure of any suggestions for the package name; there is no problem with the build process -- are you following the steps outlined [here](https://github.com/bcicen/ctop/blob/master/_docs/build.md)?

**Comment by cr6git** [comment]
See [my attempt](https://github.com/voidlinux/void-packages/issues/10923#issuecomment-361059136) at building the package for Void linux.

**Comment by bcicen** [comment]
@cr6git I had a look at your build output, it seems that it's missing some vital build flags `ctop` requires.

For at least the connectors package, `-tags release` prevents mock/test files from being included in the build.

`-ldflags "-w -X main.version=0.7 -X main.build=1c7cf98 -extldflags="-Wl,--allow-multiple-definition""` sets the version/release info and fixes some overlap in docker and runc connector implementations.

Without the ldflags above (particularly the extldflags), build will fail
