### ISSUE TITLE
I made a package in the AUR

### ISSUE THREAD

**Issue by sammko** [bcicen/ctop#12]
Great Tool!
I made a package in the [Arch User Repository](https://aur.archlinux.org/packages/ctop/). Feel free to mention it in the installation section (or not).

**Comment by bcicen** [comment]
Thanks @sammko! Added to the install docs.

**Comment by sammko** [comment]
Hi, so i renamed the package from `ctop` to `ctop-bin`. here's the new link. https://aur.archlinux.org/packages/ctop-bin/
sorry about the inconvenience.

**Comment by bcicen** [comment]
Thanks! readme updated.
