### ISSUE TITLE
Weird behaviour of ctop

### ISSUE THREAD

**Issue by Sh4d1** [bcicen/ctop#121]
Hey, 

A few weeks ago ctop stopped working, I mean it looks like that:
![2018-03-08_18 17 45_scrot](https://user-images.githubusercontent.com/990310/37165535-3123ceb4-22fd-11e8-9cc9-dc4e891f9eac.png)
I tried reinstalling ctop through AUR (I'm using Archlinux) and also downloaded the binary.
Here is the version:
```
$ ctop -v
ctop version 0.7, build 233259b go1.9.2
```

Any ideas?

Cheers,

Patrik

**Comment by bcicen** [comment]
This is due to a bug in the termbox library with ncurses 6.1; fixed now in the [latest release](https://github.com/bcicen/ctop/releases/tag/v0.7.1).

Thanks for the feedback!

**Comment by keyolk** [comment]
that was reason! sorry to duplicates.
