### ISSUE TITLE
How to escape from alt-s?

### ISSUE THREAD

**Issue by sobi3ch** [bcicen/ctop#122]
I recently installed ctop (btw great tool!) and find out that I accidentally press `alt-s` on `log view` and then couldn't exit from it. `Esc` and `q` keys didn't worked. How can I exit from container `log view` screen after entering and pressing `alt-s`?

OS: ubuntu 17.10
bash: 4.4.12(1)-release (x86_64-pc-linux-gnu)

**Comment by bcicen** [comment]
Thanks for the feedback -- alt key input was previously disabled, so `alt+s` was mistakenly being read as a non-terminated escape code.

fixed in https://github.com/bcicen/ctop/commit/842809bef5eb8be8ea248df7d0ae8d41dda97009
