### ISSUE TITLE
ugly view on screen-256 in tmux

### ISSUE THREAD

**Issue by keyolk** [bcicen/ctop#123]
I got ugly view on my tmux 

see below,
![image](https://user-images.githubusercontent.com/5329850/37955292-2c570712-31e3-11e8-87ec-acba9dac698b.png)

it become better after exporting TERM env to "xterm"
```
export TERM=xterm
```
How can I fix it on screen-256 ?

**Comment by bcicen** [comment]
Are you running Arch? This looks like the ncurses bug [here](https://github.com/bcicen/ctop/issues/121), so please make sure that you are running the latest version of `ctop` (0.7.1)

**Comment by keyolk** [comment]
that was reason! sorry to duplicates.
