### ISSUE TITLE
Logs of <ContainerName>

### ISSUE THREAD

**Issue by mykolapolonskyi** [bcicen/ctop#124]
https://github.com/bcicen/ctop/blob/master/menus.go#L182

`
m.BorderLabel = "Logs of " + c.GetMeta("name")
`

I think its nice to have container name in Logs tab title.
p.s. was fun to try install go and build ctop - nice and very useful app, tnx!

**p.p.s also its will be nice to have less command functionality in logs tab**

**Comment by bcicen** [comment]
thanks for the contribution! added in https://github.com/bcicen/ctop/commit/17855e3d8e9056d2ab7b01be9f02fc9fcb006b68.
