### ISSUE TITLE
Docker Attach Issues

### ISSUE THREAD

**Issue by superphly** [bcicen/ctop#126]
I'm using this docker-compose.yml for running ctop and it seems to be running fairly well, except for the fact that I can't interact with it when I run

`docker attach ctop`

docker-compose:
  ctop:
      name: ctop
      image: quay.io/vektorlab/ctop:latest
      restart: always
      stdin_open: true
      tty: true
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock

**Comment by bcicen** [comment]
This can be resolved by setting `TERM=linux` env var -- I've also added this as default in the [docker build](https://github.com/bcicen/ctop/commit/b83402b88626b54321b115e6d51126e545324957)
