### ISSUE TITLE
Bug: the cpu usage is incorrect

### ISSUE THREAD

**Issue by kamthamc** [bcicen/ctop#127]
The cpu usage ins incorrect. it should be valid float.

<img width="1243" alt="screen shot 2018-04-27 at 11 38 13 am" src="https://user-images.githubusercontent.com/2925876/39379270-99132dba-4a0f-11e8-8246-f5c89956c955.png">

**Comment by bcicen** [comment]
Can you provide steps to reproduce? From the screenshot, it appears this is on a non-running container?

**Comment by kamthamc** [comment]
its a running container (the green color). And its random it doesn't happen every time.

**Comment by frnhr** [comment]
I'm also seeing some nonsensical cpu usages on a singe-core AWS container running Ubuntu and docker:

<img width="1482" alt="stemi-prgm_—_ubuntu_ip-172-31-38-28____—_ssh_aws02_—_185×90" src="https://user-images.githubusercontent.com/1173748/85787185-51ad2580-b72b-11ea-924a-5e684499e5fd.png">

**Comment by oliv3r** [comment]
Probably not related; but I'm seeing some odd CPU numbers as well, https://github.com/bcicen/ctop/issues/200#issuecomment-804906125

**Comment by bcicen** [comment]
closing for https://github.com/bcicen/ctop/issues/276
