### ISSUE TITLE
[feature request] Do we need to add `inspect` for a container?

### ISSUE THREAD

**Issue by xiechengsheng** [bcicen/ctop#129]
Developers may want to know more info about this container, such as based image, network settings, etc... So can we add `inspect` function in `ctop`?

**Comment by bcicen** [comment]
Inspect details name, image, ports, etc. are [already set as arbitrary container metadata](https://github.com/bcicen/ctop/blob/master/connector/docker.go#L83); however, they could be added upon and made conditionally visible via configuration

**Comment by xiechengsheng** [comment]
Ok, I think these information should be enough for most developers~ close this.
