### ISSUE TITLE
Invert row with pointer. not only name

### ISSUE THREAD

**Issue by mykolapolonskyi** [bcicen/ctop#133]
when you have a few containers its good to have colored not only name of container where pointer is, but maybe memory field also or all raw

![image](https://user-images.githubusercontent.com/7451751/41848091-f6c10150-7884-11e8-88d1-b44e5cc35056.png)

will be much easier to find memory usage for example

**Comment by bcicen** [comment]
following up in duplicate https://github.com/bcicen/ctop/issues/139
