### ISSUE TITLE
[Feature request] Row highlighting

### ISSUE THREAD

**Issue by tonsV2** [bcicen/ctop#139]
I find it really difficult to associate the various row entries with the highlighted container name. It would be really nice to have the entire row highlighted. Even just the cpu usage bar can be hard to associate to a given container.

Thanks for a great app!

**Comment by bcicen** [comment]
full-row cursor highlighting has been added in https://github.com/bcicen/ctop/commit/cf352f7c8a9807da8341b867378905757377d174 and will be included in the next major release. Thanks!
