### ISSUE TITLE
Logs not working on MacOS

### ISSUE THREAD

**Issue by papanikge** [bcicen/ctop#144]
Hello,

sorry if there is already an issue for this but I couldn't find any.

So upon hitting `l` to get the logs of a container, it only shows the last 10(?) to me and it immediately exits to the normal screen when I hit the `up/down/j/k` keys.
I have make sure that the container I was looking into had indeed more log lines.

Could this be a problem of mine somehow, any ideas?

```
ctop version 0.7.1, build  go1.10
Mac OS X 10.11.6
```

**Comment by bcicen** [comment]
The log view currently serves to only tail a containers logs (including last 10 by default).

Opened https://github.com/bcicen/ctop/issues/157 to track implementation of a more full-featured log pager
