### ISSUE TITLE
No Memory is shown

### ISSUE THREAD

**Issue by Hackbard** [bcicen/ctop#146]
Hi there,

first to say i love your tool.
But i have the problem that i can't see the memory usage.

My System:
Debian Jessie
Docker version 17.05.0-ce, build 89658be

and i'm working only with docker-compose files.
Feel free to ask for more information if needed.

Best Regards
Hackbard

<img width="1588" alt="bildschirmfoto 2018-10-05 um 11 27 04" src="https://user-images.githubusercontent.com/971231/46527461-91fead00-c891-11e8-8c60-4735bca7c18e.png">
<img width="516" alt="bildschirmfoto 2018-10-05 um 11 26 50" src="https://user-images.githubusercontent.com/971231/46527462-91fead00-c891-11e8-88b8-bae62c71dc2b.png">

**Comment by bcicen** [comment]
@Hackbard please take a look at #45, you likely do not have memory cgroups enabled

**Comment by Hackbard** [comment]
Thanks. Worked for me!
