### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by sabrehagen** [bcicen/ctop#154]
Hi,

I'd like to make a feature request for keyboard shortcuts on the main menu. Currently it appears like this:

![image](https://user-images.githubusercontent.com/1094600/48659673-dee8bc80-eaa8-11e8-93f8-e4487a00546d.png)

And the sub-menu under `restart` appears like this:

![image](https://user-images.githubusercontent.com/1094600/48659676-f162f600-eaa8-11e8-9ea3-7d40ca88b92e.png)

It seems odd to have keyboard shortcuts on the second level menu but not on the first level. If the first level menu appeared as followed, it would make for a better keyboard user experience:

```
single [v]iew
[l]og view
[s]top
[p]ause
[r]estart
[c]ancel
```

**Comment by bcicen** [comment]
added in https://github.com/bcicen/ctop/commit/9592de82a0e5b6dcabe6d32ccef21af9b6af5262; thanks for the feedback
