### ISSUE TITLE
Exec menu option

### ISSUE THREAD

**Issue by sabrehagen** [bcicen/ctop#155]
I'd like to make a request for an `exec` option in the menu for each container:

![image](https://user-images.githubusercontent.com/1094600/48659673-dee8bc80-eaa8-11e8-93f8-e4487a00546d.png)

The most frequent command I need to perform on a container after `start` and `stop` is `exec`. Executing a command in a container (e.g. a `nslookup` a hostname, `cat` a file, get a `ps` listing) is an essential daily task, and seemingly the only operation of the docker command suite `ctop` is lacking.

I would envision the feature as an `exec` option that allowed prompted the user to enter a command to run in the container. `ctop` would then execute `docker exec -it <container-name> <provided-command>`.

**Comment by augustgerro** [comment]
Also important for me.
In `k9s` kubernetes cli client exist option connect to container via sh. I think for `ctop` it is also useful feature.

**Comment by bcicen** [comment]
closing, implemented in 0.7.3+ release
