### ISSUE TITLE
Support: What is the green plus?

### ISSUE THREAD

**Issue by sabrehagen** [bcicen/ctop#156]
What is the green plus symbol next to some containers?

![ctop](https://user-images.githubusercontent.com/1094600/48965929-7c993a00-f01b-11e8-97a1-744fb02587f1.png) 
![image](https://user-images.githubusercontent.com/1094600/48965932-a5b9ca80-f01b-11e8-9206-2d9c447c5599.png)

**Comment by bcicen** [comment]
@sabrehagen the green plus next to status indicates the container is configured with a health check command, and is in a passing state (red plus appears when health check is in a failed state)

**Comment by sabrehagen** [comment]
Thanks. This info would be useful in the docs.
