### ISSUE TITLE
undefined variables when compiling

### ISSUE THREAD

**Issue by huguesalary** [bcicen/ctop#16]
On current master branch @ddce54f991517838e1b42a27ebcfdce1c04afc72

`go build` returns:

```
# github.com/bcicen/ctop/cwidgets/expanded
ctop/cwidgets/expanded/info.go:19: p.Seperator undefined (type *termui.Table has no field or method Seperator)
ctop/cwidgets/expanded/mem.go:73: mbar.NumFmt undefined (type *termui.MBarChart has no field or method NumFmt)
```

First error is a simple spelling mistake ` p.Seperator` should be ` p.Separator`, pull request submitted (#15)

For the 2nd error, NumFmt doesn't exist. Not sure how to fix.

**Comment by bcicen** [comment]
Thanks @huguesalary. For NumFmt, this is part of a pending PR to termui: https://github.com/gizak/termui/pull/118

**Comment by mbilker** [comment]
The fork is 17 commits behind and it does not include the spelling fix for `Seperator`. Could you rebase your fork so cloning the fork allows for ctop to compile without changing `Separator` back to `Seperator`?

**Comment by bcicen** [comment]
Sure, fork is current now.

**Comment by bcicen** [comment]
Vendored deps + build steps have been merged into current master; closing this for now.

**Comment by vielmetti** [comment]
I'm following the build instructions and porting to arm64. I get this same error as reported above.
```
# github.com/bcicen/ctop/cwidgets/expanded
src/github.com/bcicen/ctop/cwidgets/expanded/mem.go:73: mbar.NumFmt undefined (type *termui.MBarChart has no field or method NumFmt)
```
```
go version go1.8 linux/arm64
```
