### ISSUE TITLE
Make Healthcheck(s) easier to see

### ISSUE THREAD

**Issue by vgoklani** [bcicen/ctop#160]
Hello - thanks for this, ctop is awesome!

Would it be possible to make the healthchecks more visible, it's hard to distinguish the various states as it's so small. Thanks!

**Comment by bcicen** [comment]
Any suggestions as to what a more visible healthcheck would look like? The current design was used to prevent a second full char width + spacing, but occupying a another column for a full-width health indicator is still an option

**Comment by djrodgerspryor** [comment]
Yeah, I'd love another column. It could even be a CLI option. I just want to be able to see at a glance if everything is healthy.

**Comment by bcicen** [comment]
Full-column healtcheck indicator added in https://github.com/bcicen/ctop/commit/4c4f041b4063898cc7f4b75402f6abc65265e52b and will be included in the next release
