### ISSUE TITLE
What do the circles and squares represent?

### ISSUE THREAD

**Issue by ovizii** [bcicen/ctop#164]
I can't find any documentation so could someone please explain what the circles and squares represent?
![image](https://user-images.githubusercontent.com/837902/51526259-423cf500-1e32-11e9-9f87-8c0a3a2cdb53.png)

**Comment by sah4ez** [comment]
Hi, @ovizii !
Squares - it's wrong images of circle :wink:  
I think you haven't a font which support this signs...
You can see screen in docs:
![screen](https://raw.githubusercontent.com/bcicen/ctop/master/_docs/img/grid.gif)
Colors represent statuses and health of the container.
green - **running** status and **healthy** health of container 
red - **exited** status  and **unhealthy** health of container
yellow - **starting** health of container
and pause sign for **paused** container.

**Comment by ovizii** [comment]
Thanks, those explanations helped a lot.

Still it seems weird, you can clearly see I have circles and squares in my image and they sometimes change so how can I miss the font? :-( besides, do you know what font it is so I can install it?

btw. what docs are you talking about? 

> You can see screen in docs:
Would you mind pointing me there please?

**Comment by sah4ez** [comment]
I'm use **Monospace Regular** font.
Docs - it's docs folder for developers... I'm about [this](https://github.com/bcicen/ctop/tree/master/_docs) directory.
You can see [here](https://github.com/bcicen/ctop/blob/master/colors.go) used colors. And [here](https://github.com/bcicen/ctop/blob/master/cwidgets/compact/status.go#L8-L10)
```go
        mark = string('\u25C9')
        healthMark = string('\u207A')
        vBar = string('\u25AE') + string('\u25AE')
```
 you can see which symbols using in ctop.

**Comment by ovizii** [comment]
ah, I see, no wonder I didn't find any "end user" documentation :-) 

Thanks for translating for me

**Comment by bcicen** [comment]
@ovizii reference doc on interpreting the status indicator [added here](https://github.com/bcicen/ctop/blob/master/_docs/status.md)

**Comment by jtagcat** [comment]
Maybe give a pointer to docs in the help (h) menu?

**Comment by jtagcat** [comment]
Also the doc mentions health checks, there's no word on it anywhere else..?
