### ISSUE TITLE
Sorting by network is wrong

### ISSUE THREAD

**Issue by demyxco** [bcicen/ctop#167]
Server 1
![screen shot 2019-03-06 at 3 30 12 am](https://user-images.githubusercontent.com/3078484/53878293-598a0900-3fc0-11e9-8fd2-be2931289e85.png)

Server 2
![screen shot 2019-03-06 at 3 30 16 am](https://user-images.githubusercontent.com/3078484/53878294-598a0900-3fc0-11e9-994a-aa2e5a95df73.png)

**Comment by bcicen** [comment]
What are you expecting to see? Both examples appear properly sorted by aggregate network traffic.

**Comment by demyxco** [comment]
@bcicen shouldn't the highest number be up top?

**Comment by bcicen** [comment]
@demyxco the highest number is on top -- Received Traffic (`RX`) + Transmitted Traffic (`TX) = Total Traffic, by which the containers are sorted

**Comment by bcicen** [comment]
closing; feel free to reopen if you still have questions
