### ISSUE TITLE
Exec shell | Flag e as mentioned in README not available in the 0.7.2 version

### ISSUE THREAD

**Issue by bharatsindhu** [bcicen/ctop#173]
As mentioned in the README file, the **EXEC functionality is not available** (Refer the attached image) ![image](https://user-images.githubusercontent.com/21232549/59618076-82f51d80-90f5-11e9-88b8-a57e2182d063.png)

I think this is the functionality that I use the most, Let me know if I have to build from the master to get the feature.

`ctop version 0.7.2, build 70bd2ae go1.11.3`

Thanks,

**Comment by liutao-me** [comment]
v0.7.2 released on Jan 24. The exec feature was merged on May 13, so you need to wait for next release, or you can build ctop from source.

I also expect the exec functionality.

**Comment by bharatsindhu** [comment]
Perfect. I was able to build from source and use the feature.
Thanks.
