### ISSUE TITLE
Add PID count support

### ISSUE THREAD

**Issue by ryanmt** [bcicen/ctop#18]
One thing I enjoy seeing from the docker stats themselves is the PID counts.  I would love to have that in this tool.  

If that's not too tricky (I'd expect it isn't), I'd be willing to tackle it.

**Comment by lifez** [comment]
I would take this PR :)

**Comment by bcicen** [comment]
Thanks for the interest @lifez! PID count support is actually already merged in https://github.com/bcicen/ctop/pull/35, and will be available in the next major release.

**Comment by bcicen** [comment]
PID support now available in [latest release](https://github.com/bcicen/ctop/releases/latest)
