### ISSUE TITLE
doesn`t work with macos catalina

### ISSUE THREAD

**Issue by ZeusFSX** [bcicen/ctop#182]
When I enter on my host via ssh from the terminal on my mac (os x 10.15) and try to run __ctop__ a got error
```error: termbox: error while reading terminfo data: termbox: unsupported terminal```

**Comment by bcicen** [comment]
Can you try ensuring you have a `TERM` environment variable set? (e.g `TERM=linux`)

**Comment by ZeusFSX** [comment]
Solved, in terminal should set ````declare terminal as xterm-256colour ````
