### ISSUE TITLE
Docker ctop (0.7.2) buggy in Alpine Linux

### ISSUE THREAD

**Issue by demyxco** [bcicen/ctop#184]
List of bugs I've seen:
* Stopping/Starting containers freezes the app
* Stopped/removed containers are still present with red status next to its name at the bottom
* Sometimes when you restart/start containers, the stats are -
* Pressing `e` on a container will open a shell and then using a text editor will show weird characters on the left side

From what I've seen, 0.7.1 does not have these issues.

**Comment by bcicen** [comment]
Thank you for the details -- many of these issues can result from redraw or screen clearing issues. If you are running ctop from within a container, please ensure you have a `TERM` environment variable set (e.g `TERM=linux`)

**Comment by demyxco** [comment]
So coming back on this, this "bug" appears when using the integrated terminal in code-server (vscode in the browser). When using a regular terminal standalone app, the bug isn't there.

**Comment by demyxco** [comment]
> If you are running ctop from within a container, please ensure you have a TERM environment variable set (e.g TERM=linux)

Added that environment variable to the container where the ctop binary is in and worked like a charm, thank you.
