### ISSUE TITLE
What is a white/grey status indicator?

### ISSUE THREAD

**Issue by dpieski** [bcicen/ctop#189]
I see the Red and Green from the status page, but what does white/grey mean?
![image](https://user-images.githubusercontent.com/3300522/71743901-52739780-2e2b-11ea-848d-d0dd8b6f36d6.png)

**Comment by bcicen** [comment]
This indicates the container is neither in a `running` or `exited` status, but a typically ephemeral status such as `restarting`, `removing`

**Comment by dpieski** [comment]
Ah thanks!
