### ISSUE TITLE
0.73 Freezing When Stopping Containers

### ISSUE THREAD

**Issue by joesixpack** [bcicen/ctop#190]
Just hangs after selecting yes.

**Comment by leszekgruchala** [comment]
It doesn't happen always, but very often for me too.

**Comment by d10xa** [comment]
It is happen always in my cases

**Comment by kmazurek244** [comment]
The same here - happens almost always. I don't remember a successful 'yes'.

**Comment by bcicen** [comment]
#201 merged; to be included in v0.7.6
