### ISSUE TITLE
Other ctop package default in Ubuntu 20.04?

### ISSUE THREAD

**Issue by rogierlommers** [bcicen/ctop#193]
After installing Ubuntu server 20.04 LTS, I found out that there is some other [ctop package](https://packages.ubuntu.com/search?keywords=ctop) installed (by default). Any idea what this is? I prefer YOUR package to be honest. Do you know the functional differences? And are your installation instructions still valid?

**Comment by cageyv** [comment]
https://github.com/yadutaf/ctop
This package is archived and not supported.
We are waiting for this version in the public repository

**Comment by rikmendes** [comment]
Trying this version on Ubuntu LTS 18 and I can't get it to work, using SSH to connect to my VPS where my docker containers are running, all I see is a black screen..i can interrupt the command, but that's it, I have no idea how I can help debug this without an error somewhere...

**Comment by bcicen** [comment]
@rikmendes if you're able to acquire the logs as outlined in the [debug doc](https://github.com/bcicen/ctop/blob/master/_docs/debug.md), feel free to include them in a new issue

**Comment by bcicen** [comment]
closing this for now; readme will be updated with install instructions when we make it to the public repos!

**Comment by dnalbach** [comment]
Thank you for posting this @rogierlommers , I thought I was going insane when `ctop` opened in 20.04 and had none of the features I'm used to.
