### ISSUE TITLE
does not run with podman?

### ISSUE THREAD

**Issue by slartibart70** [bcicen/ctop#195]
i'm using podman in rootless mode on fedora,
when running ctop i get

 [10:02:12 CEST] Get http://unix.sock/info: dial unix /var/run/docker.sock: connect: no such file or directory                      │
  │                                                                                                                                     │
  │  [10:02:12 CEST] attempting to reconnect...

**Comment by Fodoj** [comment]
It seems like  ctop works either with docker or runc (which you can specify with -contector option). Podman on Fedora is using `crun` instead of runc.

**Comment by bcicen** [comment]
Closing for now -- happy to accept a `crun` connector PR or feature request if enough demand
