### ISSUE TITLE
Incorrect Disk I/O

### ISSUE THREAD

**Issue by jonathandbackhaus** [bcicen/ctop#198]
I'm seeing writes from Disk I/O that are much lower than I would expect (i.e. by several orders of magnitude). Any thoughts on what might cause that? 

```
 NAME                           CID                            CPU                            MEM                            NET RX/TX                      IO R/W                         PIDS

   ◉  cassandra-rack2_cassandra-us-… 7a8d58c6c495                                 24%                      11.22G / 62.76G        809.45G / 3.25T                18.56G / 4M                    356
   ◉  cassandra-rack2_cassandra-us-… 426b4ea60f0d                                 14%                      11.38G / 62.76G        698.72G / 3.16T                16.64G / 3M                    335
   ◉  cassandra-rack2_cassandra-us-… af878aa525cb                                 11%                      11.23G / 62.76G        947.43G / 3.06T                17.69G / 5M                    354
```

This is true on our other Cassandra rack as well, so I'm guessing it's not a weird one-off bug. From Telegraf, I see runtime totals in the 100's of GB (e.g. 800 GB). The Disk I/O Read is also lower than expected but is at least in the ballpark. 

The CPU, memory, and network usages all look right. Any idea what's causing the discrepancy??? 

The only thing I can think of is that we have multiple volumes mounted within the container; is it possible that `ctop` isn't aggregating the data across all the volume mounts?

**Comment by bcicen** [comment]
@jonathandbackhaus thanks for the report. Upon some testing, it appears your assumption was correct -- display of aggregate I/O (across all volumes) has been fixed in https://github.com/bcicen/ctop/commit/c5038e2edd8ac6587ee2abc00d9f2bf2ffd58a86 + will be included in the next release

**Comment by jonathandbackhaus** [comment]
Thank you!
