### ISSUE TITLE
Fix CPU usage bar for many-core machines

### ISSUE THREAD

**Issue by fenollp** [bcicen/ctop#207]
Today when a container uses >100% CPU the bar behind this percentage shows as "full", thus showing that more than one core is used.

I'd prefer the bar to represent the actual usage of these cores. For instance a load of 200% on a 3 cores machine would display a bar filled to 2/3rds.

As this can make <100% loads look very tiny on many core machines, maybe this tweak should be activated only once container load goes above 100%.

**Comment by bcicen** [comment]
@fenollp have you tried running ctop with the `-scale-cpu` option?

**Comment by stokito** [comment]
This should be a config option and must be changeable as any other config (sorting, columns). I’ll prepare a PR for this.

**Comment by bcicen** [comment]
resolved in #207 with addition of new column
