### ISSUE TITLE
A dockerized ctop?

### ISSUE THREAD

**Issue by sandys** [bcicen/ctop#21]
Hi guys,
Could you build a dockerized version of ctop? Maybe using Alpine Linux or something to make it very lean ? It would be great to have a version that needs no installation

**Comment by francislavoie** [comment]
I just did that right here https://github.com/bcicen/ctop/pull/14

I tried with alpine, but it wouldn't run. I definitely would prefer alpine.

**Comment by bcicen** [comment]
added official alpine-based image and doc in https://github.com/bcicen/ctop/commit/c84b52ce40085bd3448906ab7ee29f6eecda92cc
