### ISSUE TITLE
Ctop 0.7.4 doesn't work on Ubuntu 18.04/Linux Mint 19.xx and CentOS 7.x

### ISSUE THREAD

**Issue by marcinbojko** [bcicen/ctop#213]
I understand it can be by design - but if not:
CentOS 7 ends with 2.17 version
./ctop-0.7.4-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./ctop-0.7.4-linux-amd64)
Ubuntu/Mint 19 - 2.27

**Comment by rogierlommers** [comment]
Same here; watching topic.

**Comment by DocBrown101** [comment]
Same here ...

**Comment by jilvanx** [comment]
Someone checks this PR, please

**Comment by rogierlommers** [comment]
Thanks @bcicen , works fine now 👍.
