### ISSUE TITLE
0.7.4 retag?

### ISSUE THREAD

**Issue by jonchang** [bcicen/ctop#216]
Was 0.7.4 retagged? I'm a maintainer for Homebrew and we're seeing this error on our CI:

```
Error: v0.7.4 tag should be 5b2d180f6007fb2a8387d0e821f3b80bcfc9a1cb
but is actually 426dd2c9854786bdfba7a55272256502849ccfb5
```

**Comment by bcicen** [comment]
Yes, 0.7.4 was retagged in resolving a build failure -- let me know if you need an incremented release tag (e.g. `0.7.4-2`)

**Comment by bcicen** [comment]
continuing in https://github.com/Homebrew/homebrew-core/pull/63620#issuecomment-718192397
