### ISSUE TITLE
0.7.4 Cuts off Volume Names

### ISSUE THREAD

**Issue by joesixpack** [bcicen/ctop#218]
Now limited to 12 characters.  Quite annoying.

**Comment by bcicen** [comment]
I'm assuming you're referring to container names here?

**Comment by bcicen** [comment]
fix merged in https://github.com/bcicen/ctop/pull/211 for 0.7.5

**Comment by simonc** [comment]
Hi! Thanks for this awesome tool!
Any chance 0.7.5 could be released as the milestone is complete?
The size limit currently renders `ctop` unusable as all our containers have a 10-char prefix ^^
Thanks! ❤️

**Comment by bcicen** [comment]
@simonc glad you're enjoying it :) - [v0.7.5](https://github.com/bcicen/ctop/releases/tag/v0.7.5) is now live with this fix

**Comment by simonc** [comment]
@bcicen Thanks so much! It's displaying the complete names now 😍 You rock!
