### ISSUE TITLE
[Simplification] Remove sorting by container id

### ISSUE THREAD

**Issue by stokito** [bcicen/ctop#225]
I have no idea why someone may want to sort containers by their id. Instead we can sort by name. The id column is not even shown. Will you accept a PR with removing sorting by id?

**Comment by rmdes** [comment]
That would be great indeed, my containers ID have no meaning, they are generated randomly, it's the less useful information bit of the whole thing in my view, I wish I could display their real names or even the domains each container is tied to..

**Comment by bcicen** [comment]
While IDs are randomly generated for Docker containers, I believe runc/machinectl unique container ID is still a value provided by the user. In which case viewing and sorting by ID still has value. The column may, of course, still be hidden in configuration if the user wishes. Closing for now
