### ISSUE TITLE
arm64 via raspberry pi 3 does not display memory values

### ISSUE THREAD

**Issue by MaksimAdamenko** [bcicen/ctop#227]
arm64 via raspberry pi 3, ubuntu 20.04. Does not display container memory values. I thought that this problem would be solved by a complete reinstallation of ubuntu, but everything remained the same.
![Img](https://user-images.githubusercontent.com/63460828/99267974-a580ee00-2835-11eb-8eec-e586f67cf5ef.PNG)

**Comment by bcicen** [comment]
Please confirm you have memory cgroups enabled; see https://github.com/bcicen/ctop/issues/45

**Comment by MaksimAdamenko** [comment]
It was my fault. I fixed it and now everything works fine. 
![image](https://user-images.githubusercontent.com/63460828/99443666-2ae6ca00-292c-11eb-805e-c0b6cce87f99.png)
