### ISSUE TITLE
Add GPU information

### ISSUE THREAD

**Issue by george-gca** [bcicen/ctop#237]
It would be nice if we could see which GPUs are being used by each container, even if it doesn't show how much GPU memory or processing it is consuming. Something like GPUs ids or numbers would be really useful.

**Comment by stokito** [comment]
Docker doesn't provide such kind of stats. See API response on right side:
https://docs.docker.com/engine/api/v1.40/#operation/ContainerStats

You have to ssh into server and use nvtop or something else https://www.cyberciti.biz/open-source/command-line-hacks/linux-gpu-monitoring-and-diagnostic-commands/
