### ISSUE TITLE
Handling of Shutdown-Broadcast-Messages

### ISSUE THREAD

**Issue by StefanWetterActiware** [bcicen/ctop#256]
Hi,
sorry, my knowhow of handling such messages is not at 0...

What i see:
I have a tmux session with 2 panes, ctop and iotop. iotop does NOT show these messages, ctop is filled up and the messages kill any information/readability.

I think it has something to do with the way, the information is updated, if all text is reprinted or if the shell is cleared periodically?

![grafik](https://user-images.githubusercontent.com/31532767/112218186-bb5b5100-8c23-11eb-9634-74b10baafca3.png)

Kind regards
Stefan

**Comment by bcicen** [comment]
Each row is visually refreshed when new metrics are available -- in your provided example, I believe you are only seeing messages on lines with stopped containers (not refreshing)

**Comment by StefanWetterActiware** [comment]
That sounds convincing. I close this.
