### ISSUE TITLE
Use a stable sort when sort fields are the same

### ISSUE THREAD

**Issue by Daniel15** [bcicen/ctop#257]
Given a Docker container `foo`, other containers can share its network using the `--net=foo` command-line parameter or `network_mode: service:foo` in `docker-compose.yml`. A major use case for this is routing several containers via a VPN (eg. see https://hub.docker.com/r/dperson/openvpn-client).

In this case, the network stats will be identical for every container, since it's the same network. If I sort by the `net` field in `ctop`, all the containers will be grouped together (which is correct), but their sort order will randomly jump around. It looks like you're not using a stable sort, so the sort order is essentially undefined if multiple rows have the exact same value. 

Please use a tie-breaker field (for example, when the sort field matches for two containers, also sort by the name) to ensure a stable sort.

**Comment by stokito** [comment]
the `net` means "net usage" https://github.com/bcicen/ctop/blob/master/container/sort.go#L48
you may sort my name

**Comment by Daniel15** [comment]
Interesting, looks like the sort should already be stable as it falls back to name:
https://github.com/bcicen/ctop/blob/0094cba5eaebcf478282655b1de7a8605cdbf3a9/container/sort.go#L48-L56

Not sure why the sort order is jumping around for me then.

**Comment by stokito** [comment]
probably network usage is different
