### ISSUE TITLE
I am getting an mem value from ctop that maybe inconsistent

### ISSUE THREAD

**Issue by cerealconyogurt** [bcicen/ctop#259]
Hi there,

I am having different memory value when I compare the ctop value and what I get from docker command:

![image](https://user-images.githubusercontent.com/49502224/116888762-d6918700-abf9-11eb-89db-0e6f2ee6fa56.png)

The command I run is:

`docker stats --no-stream -a --format \
"table {{.Container}}\t{{.Name}}\t{{.MemUsage}}\t{{.CPUPerc}}"`

**Comment by cerealconyogurt** [comment]
well, after a reading of a couple of forums I believe that ctop is showing the mem w/o cache usage, and now the docker is adding both mem stats in the command. I will look into this because I believe something changed in the docker command with the latest update.

I am looking for the mem stat w/o cache/buffer so ctop is showing what I need

**Comment by bcicen** [comment]
@cerealconyogurt correct, `ctop` only displays memory usage minus cache. Closing for now.
