### ISSUE TITLE
Tag naming

### ISSUE THREAD

**Issue by azlux** [bcicen/ctop#271]
FYI: @bcicen please be consistent with version tag on github, I use that for my repo pipeline for my [public repo](https://packages.azlux.fr/).
New is 0.7.6
![image](https://user-images.githubusercontent.com/11210117/122549422-be9f8680-d032-11eb-9ec2-c7852f86f726.png)
Old was  v0.7.5
![image](https://user-images.githubusercontent.com/11210117/122549510-daa32800-d032-11eb-901e-266251a8ab28.png)

**Comment by stokito** [comment]
git itself uses the `v` prefix https://github.com/git/git/releases
Previous tags was already released and published to your repo so I think you can just switch to the `v` prefixes and everything will be fine.

**Comment by azlux** [comment]
@stokito That is what i've done.
I've no problem changing the release rule check on my side.
It's just to be sure, the next release will stay with a constant name.

**Comment by bcicen** [comment]
@azlux resolved via https://github.com/bcicen/ctop/commit/c145cf404a0d558e823d207103ab0718329b1fbe

`v` prefix will remain for all future release titles + tags

additionally, I've pushed a second `v0.7.6` tag for consistency
