### ISSUE TITLE
CPU usage always 0%

### ISSUE THREAD

**Issue by Flova** [bcicen/ctop#276]
The CPU collum in the overview shows 0% for all containers since a few versions. The CPU graph in the container details page works fine tho.
I put the containers under some load and the value stays at 0% even if tho `htop` shows a CPU utilization by the processes inside the container.

![grafik](https://user-images.githubusercontent.com/15075613/131930385-097764f5-6697-4c1f-811e-3d4aa3009bd3.png)

OS: Up to date Arch Linux
Docker Version: 20.10.8
Docker API Version: 1.41
CTop Version: 0.7.6

**Comment by Flova** [comment]
Seems to be related to the newest answer in #200

**Comment by Herz3h** [comment]
Same issue here, docker 20.10.8, debian 11, ctop 0.7.6 build 8f0c9f5 go1.16.5

**Comment by linozen** [comment]
Same here, docker rootless 20.10.8, debian 11

**Comment by PriamX** [comment]
Same here. Docker version 20.10.8, fedora 34, ctop version 0.7.6, build 8f0c9f5 go1.16.5, and `docker stats` reports correctly.

**Comment by lpicanco** [comment]
Same here. 

Docker 20.10.12, build e91ed57, Debian bullseye, arm64(Pi)

Docker stats:
<img width="916" alt="Screenshot 2021-12-29 at 11 41 14" src="https://user-images.githubusercontent.com/8377/147658705-9282ef26-4498-462e-be03-e5b48a91551a.png">

ctop:
<img width="1145" alt="Screenshot 2021-12-29 at 11 41 56" src="https://user-images.githubusercontent.com/8377/147658757-8638bebf-51e8-4140-921d-8b60a389ccf3.png">

**Comment by Flova** [comment]
https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/cli/command/container/stats_helpers.go#L166

This is how it is done in the `docker stats` command.

I implemented it for `ctop` and it works. Yay.

**Comment by Flova** [comment]
I close this because the PR is merged.

**Comment by shane-axiom** [comment]
Thanks, possible to get a 0.7.7 release for this?
