### ISSUE TITLE
Legend of CTOP

### ISSUE THREAD

**Issue by alex-v-jc** [bcicen/ctop#278]
Hi.
Sorry for my question.)
But I couldn't find information anywhere on what the "plus" symbol means. 
Could you explain please?

![image](https://user-images.githubusercontent.com/35483576/138457966-1eea49ac-4374-443c-92c7-9521c9c8a01b.png)

Thanks.

**Comment by bcicen** [comment]
https://github.com/bcicen/ctop/blob/master/_docs/status.md there is a status document available; however, true, it does need to be updated for current display icons and status (possibly merged into README)
