### ISSUE TITLE
Feature request: Stopping and deleting stopped containers

### ISSUE THREAD

**Issue by gbraad** [bcicen/ctop#28]
Much like (h)top you would want to stop a container, and even delete stopped containers.

**Comment by wklm** [comment]
+1

**Comment by dodekeract** [comment]
If this gets implemented please make it hard to accidentally fuck up and delete a container.

**Comment by gbraad** [comment]
for (h)top it needs a signal to send to the process. So I could imagine typing `k` (or `s`) and confirm with `y` to stop.

**Comment by pete911** [comment]
Hi, I have create pull request #104 , have a look, let me know what you think. Basically when you hit `m` (as manage) you get menu where you can start or remove (stopped containers), or stop (running containers). Enter selects, any other key exits (there's cancel option as well).
