### ISSUE TITLE
What is green/yellow plus sign for?

### ISSUE THREAD

**Issue by PhantomRay** [bcicen/ctop#286]
Hi there,
I couldn't find any info in regards to the green or yellow plus sign to the left of the container name. Can anyone please shed some light?

**Comment by stokito** [comment]
health check

**Comment by PhantomRay** [comment]
@stokito thank you. Any more info as how it works?

**Comment by stokito** [comment]
https://docs.docker.com/engine/reference/builder/#healthcheck see HEALTHCHECK 
the basic idea is that container has a command to check itself: check connection to DB, or some metrics

**Comment by stokito** [comment]
see  #278

**Comment by PhantomRay** [comment]
Thank you Stokito!
