### ISSUE TITLE
unable to scroll down in expanded view?

### ISSUE THREAD

**Issue by evandrix** [bcicen/ctop#29]
i can't "scroll down"...help? maybe provide a `less`-like interface / `vi` key bindings

![screen shot 2017-03-10 at 10 55 26 pm](https://cloud.githubusercontent.com/assets/169669/23799796/c6feffd0-05e4-11e7-98d3-753fee3b8865.png)

**Comment by bcicen** [comment]
Expanded view scrolling added in https://github.com/bcicen/ctop/commit/12fa71682524d15939e226a57f6fcbedc30bae92, and will be included in the next major release.

**Comment by bcicen** [comment]
Vertical scrolling in expanded view enabled in the [latest release](https://github.com/bcicen/ctop/releases/latest)
