### ISSUE TITLE
go install fails

### ISSUE THREAD

**Issue by prologic** [bcicen/ctop#291]
See:

```#!sh
$ go install github.com/bcicen/ctop@latest
go: downloading github.com/bcicen/ctop v0.7.6
go install: github.com/bcicen/ctop@latest (in github.com/bcicen/ctop@v0.7.6):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

I notice there is a `replace` directive in the `go.mod` file. We should not do this. Perhaps let's upgrade the dependency or fix what issue it has upstream? Or fork it.

**Comment by bcicen** [comment]
replace directive has been removed in https://github.com/bcicen/ctop/commit/6dcb62f172bbb042893f81c7004c1ab361724a63
