### ISSUE TITLE
When compiled on arm memory shows zero

### ISSUE THREAD

**Issue by jturning** [bcicen/ctop#318]
ctop version 0.7.7, build 59f00dd go1.19.2

Linux raspberrypi 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux

![screenshot 3](https://user-images.githubusercontent.com/37452682/197344128-e6f71c2a-0b3f-4389-8829-c951178c2544.jpg)

**Comment by wouterds** [comment]
This is unrelated to the tool. You need to edit `/boot/cmdline.txt` & add `cgroup_enable=memory cgroup_memory=1` at the end if you want to view resources of Docker containers on Raspberry Pi.

**Comment by jturning** [comment]
That did the trick. Thank you.
