### ISSUE TITLE
Support for Alacritty

### ISSUE THREAD

**Issue by inta** [bcicen/ctop#342]
Do you have any plans to support Alacritty? I have no idea how terminal emulators differ, I just got the following error on execution:
```
panic: termbox: error while reading terminfo data: termbox: unsupported terminal [recovered]
        panic: termbox: error while reading terminfo data: termbox: unsupported terminal

goroutine 1 [running]:
main.panicExit()
        /home/bradley/repos/bcicen/ctop/main.go:137 +0x4d
panic({0xa15220, 0xc000286760})
        /usr/lib/go/src/runtime/panic.go:838 +0x207
main.main()
        /home/bradley/repos/bcicen/ctop/main.go:94 +0x627
```

**Comment by davidzx** [comment]
works great on arch/archarm with alacritty

**Comment by inta** [comment]
Which version of Alacritty are you using? I just realized I am still on 0.11.0 so maybe I could just go ahead and upgrade to the latest one.

**Comment by davidzx** [comment]
> Which version of Alacritty are you using? I just realized I am still on 0.11.0 so maybe I could just go ahead and upgrade to the latest one.

0.12.3 from the arch repo
https://archlinux.org/packages/?sort=&q=alacritty

**Comment by inta** [comment]
Thank you, that did it, ctop is working fine with Alacritty 0.12.3 :+1:
