### ISSUE TITLE
Ubuntu 24 installation

### ISSUE THREAD

**Issue by hubertsvk** [bcicen/ctop#357]
Ubuntu has connect to internet without problems

martin@ubuntudock:/docker/csirt$ _sudo apt-get install ca-certificates curl gnupg lsb-release
curl -fsSL https://azlux.fr/repo.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/azlux-archive-keyring.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian \
  $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azlux.list >/dev/null_
sudo apt-get update
sudo apt-get install docker-ctop
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203).
curl is already the newest version (8.5.0-2ubuntu10.4).
gnupg is already the newest version (2.4.4-2ubuntu17).
lsb-release is already the newest version (12.0-2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Hit:1 https://download.docker.com/linux/ubuntu noble InRelease
Hit:2 http://sk.archive.ubuntu.com/ubuntu noble InRelease
Hit:3 http://sk.archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:4 http://sk.archive.ubuntu.com/ubuntu noble-backports InRelease
Ign:5 http://packages.azlux.fr/debian noble InRelease
Hit:6 http://security.ubuntu.com/ubuntu noble-security InRelease
**Err:7 http://packages.azlux.fr/debian noble Release
  404  Not Found [IP: 37.58.181.100 80]**
Reading package lists... Done
**E: The repository 'http://packages.azlux.fr/debian noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.**
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
**E: Unable to locate package docker-ctop**

**Comment by hubertsvk** [comment]
I changed noble to bullseye and 

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
**E: Unable to locate package ctop**

**Comment by jwjacobs88** [comment]
I was able to install on 24.04 by adding 
```
Enabled: yes
Types: deb
URIs: http://packages.azlux.fr/debian/
Suites: stable
Components: main
Signed-By: /usr/share/keyrings/azlux-archive-keyring.gpg
```
to `/etc/apt/sources.list.d/third-party.sources`

and then doing `sudo apt-get update && sudo apt-get install docker-ctop`

**Comment by hubertsvk** [comment]
aaaaleluja :) thank you [jwjacobs88](https://github.com/jwjacobs88) it`s works now, thank you again

**Comment by hubertsvk** [comment]
https://github.com/bcicen/ctop/issues/357#issuecomment-2395124593
