### ISSUE TITLE
Feature request: set update interval

### ISSUE THREAD

**Issue by aleveille** [bcicen/ctop#39]
It would be nice to add support for changing the update interval. Like `top`, a key (`d` and/or `s`?) could be used to change the refresh interval from the default value to another value.

Also, if that feature is added, perhaps the default refresh interval can be increase to 3.0 seconds, like top? 

If that sounds like something that would add value to the project, I can start working on it.

**Comment by bcicen** [comment]
Update interval would be nice; however, in the case we would only be changing the screen refresh interval, as docker stat collection still has a static stream interval of per-second.

**Comment by pete911** [comment]
@aleveille do you still think update interval is setting is still relevant? Reading @bcicen answer, you could set only how often UI refreshes, so basically you could only set it to refresh less often than every second. And even that wouldn't speed up, or save resources (docker stat will still send every second). Is that correct @bcicen ?

**Comment by bcicen** [comment]
closing as we are mostly bound to the interval at which the API streams stats to us (for Docker at least)
