### ISSUE TITLE
Some keyboard command suggestions

### ISSUE THREAD

**Issue by firecat53** [bcicen/ctop#4]
Hey, great job! Very handy! A few opinions on keyboard commands:

1. Add j-k for up/down navigation
2. Instead of a separate menu for sorting, use 'n' - name, 'c' - cpu, 'i' - id, 'm' - mem, '%' - mem%, N - net, 's' - state. Another option would be to match the 'htop' shortcuts as close as possible ('M' - mem, 'P' - cpu, etc). 
3. Add '?' as a trigger for the help menu

Just my two cents. Feel free to close if you've got other plans :smile:

Scott

**Comment by yangmillstheory** [comment]
Requuesting C-j, C-k, C-n, C-p for up/down navigation.

Also what about the ability to kill/stop containers interactively?

**Comment by bcicen** [comment]
`j`/`k` navigation is enabled in the [latest release](https://github.com/bcicen/ctop/releases/latest)

further custom keybindings is an option in the future; however, with a growing number of metrics/columns, sort field hotkeys may not be feasible.

**Comment by bcicen** [comment]
closing this for now; updates for config file and custom keybindings can be tracked in https://github.com/bcicen/ctop/issues/53
