### ISSUE TITLE
PageUp and PageDown support

### ISSUE THREAD

**Issue by Ka1wa** [bcicen/ctop#44]
Nice tool!

We're running hundreds of containers and it's kind of exhausting to scroll through. Supporting Page up and Page down would really help!

Thanks!

**Comment by bcicen** [comment]
adding this to the roadmap for the next release.

fyi, if your terminal emulator supports it, you can use mouse scrolling to move quickly through the list as well.

**Comment by yashpatel5400** [comment]
Working on this -- should have a pull request out for it sometime tonight

**Comment by yashpatel5400** [comment]
Just submitted a pull request to add this feature at #61

**Comment by bcicen** [comment]
merged in [latest release](https://github.com/bcicen/ctop/releases/tag/v0.6.0)
