### ISSUE TITLE
homebrew formula

### ISSUE THREAD

**Issue by avelino** [bcicen/ctop#5]

**Comment by bknowles** [comment]
👍

**Comment by bcicen** [comment]
@avelino per https://github.com/bcicen/ctop/issues/33, the homebrew formula can be updated as below to provide build from source:

```ruby
class Ctop < Formula
  desc "Top-like interface for container metrics"
  homepage "https://bcicen.github.io/ctop/"
  url "https://github.com/bcicen/ctop/archive/v0.4.1.tar.gz"
  sha256 "bc10b774dad0bc7ef0be41bcfb36c774fc28dafa789b2f43f1ecdb5b75390867"

  depends_on "go" => :build
  depends_on "glide" => :build
  bottle :unneeded

  def install
    ENV["GOPATH"] = buildpath
    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"
    dir = buildpath/"src/github.com/bcicen/ctop"
    dir.install Dir["*"]
    cd dir do
      system "glide", "install"
      system "go", "build", "-o", bin/"ctop"
    end
  end

  test do
    system "#{bin}/ctop", "-v"
  end
end
```

**Comment by avelino** [comment]
@bcicen release 0.4.1 not exist glide file
```
[ERROR] Failed to find glide.yaml file in directory tree: Cannot resolve parent of /
```

Generate new release pls

**Comment by bcicen** [comment]
Sure, code-only 0.4 release with glide published [here](https://github.com/bcicen/ctop/releases/tag/v0.4.1-deps).

url: `https://github.com/bcicen/ctop/archive/v0.4.1-deps.tar.gz`
sha256: `39c4247a7c6715bc45db078769419ff9bdab1219378ac39cb97febbc0130dbf5`

**Comment by MichielDeMey** [comment]
Looks like `ctop` is available on Homebrew now. 😎
http://braumeister.org/formula/ctop

Simply `brew install ctop`

**Comment by bcicen** [comment]
added to readme as well; thanks @avelino!

**Comment by cemo** [comment]
I am using by brew btw. Thanks for your efforts guys.
