### ISSUE TITLE
ctop config file

### ISSUE THREAD

**Issue by bcicen** [bcicen/ctop#53]
Possible capabilities:
 * custom/additional keybinds
 * color scheme modification
 * default view (all containers vs running containers)

**Comment by ryanmt** [comment]
I'd also love to alter the columns visible in a config.

**Comment by kenan-rhoton** [comment]
Maybe we could use TOML for the file format? https://github.com/BurntSushi/toml

I could hack something up with that relatively quickly (and it would be a very helpful feature to me 😄 )

**Comment by kenan-rhoton** [comment]
@bcicen, any comments on the config file?

**Comment by bcicen** [comment]
Config file support has been added in the latest [v0.7](https://github.com/bcicen/ctop/releases/latest) release; details are added to the [README](https://github.com/bcicen/ctop#config-file) as well
