### ISSUE TITLE
Memory usage and PIDs not shown

### ISSUE THREAD

**Issue by cvette** [bcicen/ctop#54]
Running ctop version 0.5, build a87bdce on Debian 8.7. It doesn't show the memory usage and PIDs for me, even when running as root.

**Comment by bcicen** [comment]
If you're referring to the memory column showing "0B/0B", take a look at https://github.com/bcicen/ctop/issues/45

**Comment by bcicen** [comment]
closing for now, feel free to re-open if the issue persists
