### ISSUE TITLE
Add support for TLS protected access

### ISSUE THREAD

**Issue by zette** [bcicen/ctop#55]
There seems to be no way to specify certificate and key to access remote docker engine via TLS protected connection.
Setting DOCKER_HOST to:

`export DOCKER_HOST=tcp://address:port DOCKER_TLS_VERIFY=1`

forced ctop to https/tls mode, but there is no way to specify key needed to authenticated with remote demon.

Details can be found here: https://docs.docker.com/engine/security/https/

**Comment by bcicen** [comment]
at the bottom of the doc you've linked are examples of how to configure your cert/key path via `DOCKER_CERT_PATH` env var

**Comment by zette** [comment]
Yes, but selection of auth mode is now available via variables. One need a way to choose from:
`Client modes
tls: Authenticate server based on public/default CA pool
tlsverify, tlscacert: Authenticate server based on given CA
tls, tlscert, tlskey: Authenticate with client certificate, do not authenticate server based on given CA
tlsverify, tlscacert, tlscert, tlskey: Authenticate with client certificate and authenticate server based on given CA`

**Comment by bcicen** [comment]
As `tlscacert`, `tlscert`, and `tlskey` all have default client values, the client modes section is only describing how the client will be configured if those certs/keys are found and/or `tlsverify` is enabled. Those options are all directly passed into the http client [tls.Config](https://golang.org/pkg/crypto/tls/#Config).

In cases where you would want to enable `tls`, but not `tlsverify`, it seems there is no way to configure this via env var. You may want to open an issue with Docker on this, or follow one of the issues related to [adding tls to client configuration file](https://github.com/docker/docker/issues/30591)

**Comment by bcicen** [comment]
closing for now, as all of the client configuration is upstream in the docker main project. Feel free to re-open with any questions.
