### ISSUE TITLE
Add exec

### ISSUE THREAD

**Issue by marvinwankersteen** [bcicen/ctop#56]
Very nice tool!
I have some features that would be nice if you can build that in your tool.
- Show logs of an container like `docker logs -f [--tail=x] <container>`
- Exec like `docker exec -ti <container> bash`

**Comment by wannaknowmo** [comment]
these two features would be awesome.

**Comment by kenan-rhoton** [comment]
So pretty much both of these features require that we close and reinit the termui properly, however there is currently a bug in termui which makes this simply not work correctly.

I've however submitted a pull request there which fixes the bug. As soon as it's fixed I'll set up a pull request for the Exec feature (I've already got it working except for that issue).

@bcicen, would it be possible to add that fix to your termui fork which we're using until they accept your numfmt change? That would speed up the process

**Comment by wannaknowmo** [comment]
@kenan-rhoton thanks for following up

**Comment by pete911** [comment]
hi, I have created pull request #105 to view logs
