### ISSUE TITLE
[RFC] runC support

### ISSUE THREAD

**Issue by glestaris** [bcicen/ctop#63]
Many container engines are today built on [runC](https://github.com/opencontainers/runc). A few notable examples:

* Docker
* [Cloud Foundry Garden](https://github.com/cloudfoundry/garden-runc-release/tree/master)
* Kubernetes [CRI-O](https://github.com/kubernetes-incubator/cri-o)

Wonder if we could make ctop work with runC? It would have to be on the host that's running runC containers but that's probably not too much to ask.

WDYT?

**Comment by glestaris** [comment]
@williammartin

**Comment by glestaris** [comment]
@cloudfoundry/cf-garden

**Comment by bcicen** [comment]
`runC` support is certainly possible, as [libcontainer](https://github.com/opencontainers/runc/blob/master/libcontainer/container_linux.go) does export the `Stats()` method (for Linux containers only)

**Comment by bcicen** [comment]
An initial runc connector implementation is available on the [runc branch](https://github.com/bcicen/ctop/tree/runc).

Running via docker:
```bash
docker run --rm -ti --name ctop \
  -v /run/runc:/run/runc \
  -v /sys:/sys \
  --pid=host \
  quay.io/vektorlab/ctop:runc --connector runc
```

Containers created via docker will be missing names and some other metadata; however stat collection and all other functionality is available.

**Comment by bcicen** [comment]
merged in [latest release](https://github.com/bcicen/ctop/releases/tag/v0.6.0)
