### ISSUE TITLE
Does not work on musl libc / Alpine Linux

### ISSUE THREAD

**Issue by zaolin** [bcicen/ctop#64]
Hey,

it seems there is no support for the musl libc / alpine environment.
Maybe it's easy to fix that, projects like caddy supporting musl as well. :)

Regards, Zaolin

**Comment by bcicen** [comment]
The official image (`quay.io/vektorlab/ctop:latest`) ships as a standalone binary and does not require glibc -- in fact, the [build environment](https://github.com/bcicen/ctop/blob/master/Dockerfile_build) for this is based on Alpine.

Alternatively, you may build your own image or binary by following the steps in the [build doc](https://github.com/bcicen/ctop/blob/master/_docs/build.md)

**Comment by bcicen** [comment]
closing for now; feel free to re-open if you're still having issues.
