### ISSUE TITLE
Port and build on linux-arm64 (ARMv8, aarch64)

### ISSUE THREAD

**Issue by vielmetti** [bcicen/ctop#68]
What I saw: binaries for linux-arm (ARMv7, 32-bit) in the release directory.

What I expected to see: also binaries for linux-arm64 (ARMv8, 64-bit) in that same directory.

I think the fix is a one-liner in the Makefile, at https://github.com/bcicen/ctop/blob/master/Makefile#L20 and I'll have a PR to that effect.

thanks!

**Comment by vielmetti** [comment]
I ran into #16 on the way there.

**Comment by bcicen** [comment]
As mentioned in the [build doc](https://github.com/bcicen/ctop/blob/master/_docs/build.md) and #16, build dependencies have since been vendored so you will need to install them via `glide install`
