### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by francislavoie** [bcicen/ctop#7]
Steps:

1) Hit `f` to filter
2) Type a filter that will yield 0 results (e.g. `sdjkfhljkghlksdfh`)
3) Hit `Enter` to save the filter
4) Hit `Enter` again
5) Program dies

If there's no containers listed it can't go into the container-specific view.

**Comment by bcicen** [comment]
Thanks for the feeback @francislavoie; this should definitely be an easy fix. Will get it added to the next minor release.

**Comment by bcicen** [comment]
fixed in [latest release](https://github.com/bcicen/ctop/releases/tag/v0.4.1)
