### ISSUE TITLE
exit from select 's' menu using 'esc' instead of 'q'

### ISSUE THREAD

**Issue by pete911** [bcicen/ctop#70]
I find it a bit confusing that from 'f' filter menu I exit using 'esc' (which is obvious), but to exit from 's' select menu I need to use 'q'. It should be 'esc' to make it consistent.

**Comment by bcicen** [comment]
this is due to the input nature of the filter menu -- `enter` will exit the dialog, retaining the filter as applied; `esc` will exit the dialog and clear/reset the filter

**Comment by bcicen** [comment]
seems that allowing "exit" keys group + `enter` to exit the dialog, while retaining the filter, would provide the most consistent experience.

**Comment by bcicen** [comment]
This is implemented in the [latest release](https://github.com/bcicen/ctop/releases/latest) -- `<enter>` still closes the dialog with the filter applied, while`<esc>` will close the dialog and clear the filter.
