### ISSUE TITLE
Scrolling through container list pegs CPU

### ISSUE THREAD

**Issue by vielmetti** [bcicen/ctop#72]
If I hold down the 'j' key on the main screen to scroll through the container list,  I can convince 'ctop' to spike CPU usage.

What I expected: 'j' key to move to next line is an inexpensive operation, as is 'k' to move up.

What I got: CPU usage of `ctop` peaked at 80% during operations, then returned quickly to zero.

How invoked: `ctop` shell script on macos 10.11.6, docker Version 17.04.0-ce-mac7 (16352) / Channel: edge / b598153e23

```
#!/bin/sh
docker run -ti --name ctop --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop:latest
```

```
quay.io/vektorlab/ctop                       latest                        9b46336d11f0        2 days ago          5.59MB
```

**Comment by bcicen** [comment]
`ctop` avoids the expense of rendering per-row widgets when they are off-screen. As a result, the view and all displayed widgets must be re-aligned and re-drawn when scrolling through pages.
 
`<pgup>` and `<pgdown>` do mitigate this slightly by allowing page scrolling.

**Comment by bcicen** [comment]
One possible solution to alleviate load would be to suspend automatic(per-second) screen redraws temporarily while scrolling.

**Comment by bcicen** [comment]
per-second screen redraws are disabled during scrolling in the latest version; closing
