### ISSUE TITLE
I/O metrics?

### ISSUE THREAD

**Issue by JayAndCatchFire** [bcicen/ctop#74]
ctop is awesome!  Great tool.  It already tracks CPU, memory, and network usage.  But I'd also find it very useful to see metrics related to disk I/O, both inside and outside the container.  Would such a feature be possible?

**Comment by kenan-rhoton** [comment]
I think something similar to my ports pull request could be done... I might get on it :)

**Comment by JayAndCatchFire** [comment]
Bytes read/sec and bytes written/sec.  Although metrics from within the union fs would be useful, I'd find metrics regarding reads and writes that traverse the container-host barrier to be the most helpful.

**Comment by kenan-rhoton** [comment]
Aren't those already in the expanded view?

**Comment by JayAndCatchFire** [comment]
Believe it or not, I've never looked at the expanded view. I'm going to
have to check that out tomorrow to be sure.

**Comment by bcicen** [comment]
Block I/O metrics were added in [v0.5](https://github.com/bcicen/ctop/releases/tag/v0.5), both in the compact view and the expanded view.

**Comment by JayAndCatchFire** [comment]
Feel free to close this issue.
