### ISSUE TITLE
Add support for healthcheck (feature request)

### ISSUE THREAD

**Issue by MetalArend** [bcicen/ctop#76]
In Docker 1.13, health check of containers and services was added. Could ctop support the Dockerfile HEALTCHECK command and/or the docker-compose healthcheck for containers? And could it support the swarm healthcheck option for services?

Awesome job btw, have been running ctop for the last few days, thanks for all the time and effort put into it!

**Comment by kenan-rhoton** [comment]
This shouldn't be TOO hard to add, I feel, I might give it a shot :smiley:

**Comment by MetalArend** [comment]
That would be so frikkin awesome!

**Comment by sah4ez** [comment]
#88 
Someone get look at my pull-request?

**Comment by bcicen** [comment]
I've merged the PR from @sah4ez providing health check status, which relays health check status by changing the color of the container name column.

I have an additional update that would provide health check status alongside the existing status indicator:
![health](https://user-images.githubusercontent.com/5673805/29755945-47989d4c-8bda-11e7-9eca-5be485726e6b.png)

Thoughts?

**Comment by bcicen** [comment]
health indicator updates have been merged to master and will be included with the next release
