### ISSUE TITLE
memory values are not displayed

### ISSUE THREAD

**Issue by eqms** [bcicen/ctop#77]
The memory values of my container display only 0B / 0B.
If I add 

export DOCKER_HOST=tcp://127.0.0.1:4243

$ ctop
panic: cannot connect to Docker endpoint

I am using Debian Jessie with Docker version 1.13.0, build 49bf474

**Comment by bcicen** [comment]
please take a look at https://github.com/bcicen/ctop/issues/45

**Comment by eqms** [comment]
Thanks for the fast help and the great tool!
