### ISSUE TITLE
Feature request: Remember previous view settings

### ISSUE THREAD

**Issue by wulftone** [bcicen/ctop#78]
Somewhat related to https://github.com/bcicen/ctop/issues/53, but just having a memory of view settings (filtering, too, maybe?) between invocations, as opposed to--or in conjunction with--initial startup settings.

**Comment by bcicen** [comment]
config file support has been added in the latest [v0.7](https://github.com/bcicen/ctop/releases/latest) release. Simply use the `S` keybinding to save the current view/filters/etc.
