### ISSUE TITLE
Memory usage displays 0

### ISSUE THREAD

**Issue by saabeilin** [bcicen/ctop#79]
On my system (3 hosts), I always have 0 memory displayed:

![image](https://user-images.githubusercontent.com/1620799/27102632-3a9afc46-5086-11e7-8f50-849ef3f59649.png)

```
$ docker --version 
Docker version 17.03.1-ce, build c6d412e

$ uname -a
Linux data0 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

$ ctop -v
ctop version 0.5, build a87bdce
```

P.S. Works as expected on Ubuntu 4.4.0-78-generic (same docker and ctop versions)

**Comment by bcicen** [comment]
@saabeilin please take a look at https://github.com/bcicen/ctop/issues/45

**Comment by saabeilin** [comment]
Closing as obvious duplicate, thanks!
