### ISSUE TITLE
Port information reversed to what standard docker tools display

### ISSUE THREAD

**Issue by dodalovic** [bcicen/ctop#80]
Hi, thanks for nice work!
One thing, I noticed that ctop displays port something like this:
![image](https://user-images.githubusercontent.com/6358061/27256055-534f9eb8-53ab-11e7-8c25-f2f27cab4704.png)

whereas standard docker tools reverse inner/outer ports mapping info:
![image](https://user-images.githubusercontent.com/6358061/27256057-619a5030-53ab-11e7-879f-a75f278fd148.png)

This is confusing.

**Comment by bcicen** [comment]
Good point @dodalovic -- this has been reversed in https://github.com/bcicen/ctop/commit/58d9e4e194a010a9b8cb2eb3537987f9d87497bd
