### ISSUE TITLE
Runc and Docker swarm mode

### ISSUE THREAD

**Issue by sah4ez** [bcicen/ctop#89]
Hi @bcicen,
 I right understand, that `swarm.Node` and `swarm.Service` allowed only for `connector.docker.go`? And for `runc` mode, swarm mode will be not available.

**Comment by bcicen** [comment]
Correct. I don't see a way forward with swarm support that doesn't required a stats forwarder/proxy deployed to each node in the cluster

**Comment by bcicen** [comment]
closing for #46
