### ISSUE TITLE
Docker API

### ISSUE THREAD

**Issue by sah4ez** [bcicen/ctop#91]
Hi!
Why are use [fsouza API](github.com/fsouza/go-dockerclient)?
This API hasn't `Attachable` option for `Network`.

May be use [moby API](https://github.com/moby/moby/tree/master/client) or [docker API](https://github.com/docker/docker/tree/master/client)?

**Comment by bcicen** [comment]
The fsouza package does in fact overlay the moby API already; though, it could be beneficial going forward to use the moby api package directly.
