### ISSUE TITLE
Docker 1.20 api version support

### ISSUE THREAD

**Issue by deepakchoudhary** [bcicen/ctop#92]
I am using docker api version 1.20. 
ctop shows all containers names and cids but none of the metrics.

ubuntu@server:~$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

**Comment by deepakchoudhary** [comment]
![screenshot from 2017-09-05 20-39-39edited](https://user-images.githubusercontent.com/3988170/30068209-ad9ad1c2-927a-11e7-975e-0b547b4740ec.png)
the screenshot of the output is attached

**Comment by bcicen** [comment]
@deepakchoudhary the structure of docker `stats` API has had many changes since 1.8.1 release two years ago, so it's unlikely to be supported in the future.

`ctop` should work with any docker version after 1.12

**Comment by bcicen** [comment]
closing
