### ISSUE TITLE
Binary file size

### ISSUE THREAD

**Issue by olegstepura** [bcicen/ctop#93]
Hi!

I suggest to add some description to the readme why the binary file size is so big. 
`htop` for example is 134K in size. And when compared `ctop` looks suspiciously bigger.

**Comment by purplesrl** [comment]
That's because htop is probably made in C, and ctop in GO. GO usually create large binaries because it does not have dependencies, meaning you can run the binary on any system without installing extra packages.

**Comment by bcicen** [comment]
@purplesrl summed this up nicely; closing for now.
