### ISSUE TITLE
Consider securing http://ctop.sh with HTTPS (LetsEncrypt?)

### ISSUE THREAD

**Issue by Jorl17** [bcicen/ctop#95]
Hi,

First of all let me thank you for such a wonderful project. We've been using it for a while and it's just one of those tools which you learn to love and can't go without.

I would like to suggest that you take some small time to move http://ctop.sh to HTTPS. HTTP websites can lead to privacy issues even if there is absolutely no private data on the site itself. An attacker can easily Man-in-the-middle a user and look for HTTP connections, including ctop.sh, to spoof users, create fake links, inject malicious code, etc. I personally believe that all websites should serve content over HTTPS, especially when it is so easy to do so nowadays with LetsEncrypt. I would also advise enabling HSTS, which takes generally only 1 line in a typical nginx/apache server configuration.

I decided to open this issue because I keep coming back to this project again and again, with every new docker-enabled deployment, and so I thought I'd suggest it. I would understand if this were discarded as something of less importance, although I still firmly believe we should all do our part in making the web a safer place.

Thanks again for this wonderful project!

**Comment by bcicen** [comment]
Glad you're enjoying ctop @Jorl17!

Thanks for the suggestion; the [ctop landing page](https://ctop.sh) is now fully HTTPS.
