### ISSUE TITLE
new feature: connect to database and store monitored data

### ISSUE THREAD

**Issue by xiechengsheng** [bcicen/ctop#96]
Sometimes developers would like to store the monitored data into a database(time series database, such as influxdb) and use such data to analyze the expression of containers. It would be great if ctop can store data into a database~

**Comment by pete911** [comment]
I feel like you are describing [cadvisor](https://github.com/google/cadvisor) here. I kind of like that `ctop` is easy to install and run, no db required. I think that they are two different tools for different use cases.

**Comment by bcicen** [comment]
@pete911 agreed; this is largely outside the scope of ctop currently.

In the future, support for multi-host/cluster monitoring will likely make the stat collector/aggregator capable of running headless, which could be potentially paired with an external shipper to store results in an arbitrary database.

closing for now.
