### ISSUE TITLE
Unrecognized containers

### ISSUE THREAD

**Issue by oxblue-rbollig** [bcicen/ctop#97]
I just installed ctop using the script for Linux in the readme.

When I run it, I see three containers that are not mine.  Is it accidentally pointed at a test server, perhaps?

Containers shown in ctop:
![ctop wrong containers](https://user-images.githubusercontent.com/22841001/30938910-bc35c79c-a3a9-11e7-8549-822b47c12758.png)

My containers:
![my containers](https://user-images.githubusercontent.com/22841001/30938916-bed31a68-a3a9-11e7-989f-d6787b6067c9.png)

**Comment by bcicen** [comment]
@oxblue-rbollig can you check against your local `$DOCKER_HOST` and `docker ps -a` output?

**Comment by oxblue-rbollig** [comment]
Ah, drat!  They are **docker** containers on my local system, not **LXD** containers.

Documentation says 

> ctop comes with built-in support for Docker and runC; connectors for other container and cluster systems are planned for future releases.

So, this is not a bug.  Sorry!
