### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by Webysther** [bcicen/ctop#98]
ctop on docker don't get timezone from system.

**Comment by bcicen** [comment]
@Webysther can you provide more info on the OS/platform you are using? Timezone should taken directly from the system.

**Comment by Webysther** [comment]
Ubuntu 16.04. Sorry, i forget very important information, i'm using inside docker with alias:

```shell
alias dtop='docker run -ti --name ctop --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop:latest'
```

**Comment by bcicen** [comment]
@Webysther the container is using UTC by default; if you want to use the same timezone as the host, try adding `-v /etc/localtime:/etc/localtime:ro` to your alias.
