### ISSUE TITLE
Easier installation route

### ISSUE THREAD

**Issue by Southclaws** [bcicen/ctop#99]
Loving this tool! It does what Portainer doesn't currently: overview of all container resource usage.

But installation was a little on the rough side, nothing a little bash script won't fix!

I had to chown and chmod the binary in `/usr/local/bin` in order to use it. I also noticed how the version was hard-coded into the readme - I'm not sure if you automate this when you release a version but still, I think a quick one-liner would be a nice solution, [something like this](https://github.com/Southclaws/sampctl/wiki/Linux) that runs [something like this](https://github.com/Southclaws/sampctl/blob/master/linux-install.sh) (which grabs the latest release via GitHub API) combined with GoReleaser would definitely make that process easier for the maintainers(s) and quicker for the user 👍

**Comment by bcicen** [comment]
@Southclaws there are a host of install options already, but I've added a install script for those who prefer that route:
```curl https://raw.githubusercontent.com/bcicen/ctop/master/install.sh | sh```
